### ISSUE TITLE
On Individual Request Pages, Remove Repetative Text

### ISSUE THREAD

**Issue by kateblanch** [WaltersArtMuseum/walters-api#70]
For example, on objects-get.md, it is confusing to see this block of text repeated. 
I think it's clearer to just list the parameters. However, you may have good logic for repeating it - so just an idea to streamline, not urgent.

My suggestion would be to remove this text from objects-get.md --

Get Object

An object is a piece of art, an artifact or similar item within the Walters collections. Each object has several properties, a unique ID and a number of images of various sizes. For example, an object could be the painting on canvas titled "The Ideal City" by artist Fra Carnevale, dating from the Renaissance, ca. 1480-1484. The resource URL for this object is http://art.thewalters.org/detail/37626. Another example of an object is an earthenware "Camel" created in China, dating from the 7th-8th century. The resource URL for this object is http://art.thewalters.org/detail/7363.

This is one of 3 requests you can use to get museum objects:

GET v1/objects Get museum objects via a number of parameters.
GET v1/objects/{id} Get extended details about a museum object by referencing an object ID.
GET v1/objects/{id}/images Get images of a museum object by referencing an object ID.
A Note about Images

Wherever you see an image string reference in the API, you can manipulate it. There are some important options and features to understand about the images available through the Walters Art Museum API.

**Comment by dylan-k** [comment]
I have begun to address this issue with commit #a95d970a12084db14ba136d2333fd49789762336 

Take a look, and if you think this is fixed, we can close this issue.

**Comment by kateblanch** [comment]
Looks great, ok to close. THANK YOU!
